name: Super Linter

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    
    - name: Lint Code Base
      uses: github/super-linter@v3
